import PDFDocument from "pdfkit";
import type { Response } from "express";

// Colors match frontend/src/styles/tokens.css so the PDF and the
// web UI feel like the same product, not a generic invoice template.
const INK = "#16233f";
const INK_SOFT = "#4a5570";
const GOLD = "#c98a1f";
const RULE = "#d8d6cc";

interface InvoiceForPdf {
  number: string;
  createdAt: Date;
  type: string;
  status: string;
  subTotal: number;
  taxTotal: number;
  discount: number;
  grandTotal: number;
  amountPaid: number;
  dueDate?: Date | null;
  notes?: string | null;
  terms?: string | null;
  business: { name: string; gstin?: string | null; address?: string | null; ownerName?: string | null; ownerPhone?: string | null; stateName?: string | null };
  customer?: { name: string; phone?: string | null; gstin?: string | null } | null;
  items: { name: string; quantity: number; unitPrice: number; taxRate: number; lineTotal: number }[];
}

export function generateInvoicePdf(invoice: InvoiceForPdf): Promise<Buffer> {
  return new Promise((resolve, reject) => {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

  // Header
  doc.fontSize(20).fillColor(INK).text(invoice.business.name, { continued: false });
  if (invoice.business.gstin) {
    doc.fontSize(9).fillColor(INK_SOFT).text(`GSTIN: ${invoice.business.gstin}`);
  }
  if (invoice.business.address) {
    doc.fontSize(9).fillColor(INK_SOFT).text(invoice.business.address);
  }
  const businessContact = [invoice.business.ownerName, invoice.business.ownerPhone, invoice.business.stateName].filter(Boolean).join(" | ");
  if (businessContact) doc.fontSize(9).fillColor(INK_SOFT).text(businessContact);

  doc.moveDown(1);
  doc.strokeColor(RULE).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.8);

  // Invoice meta
  doc.fontSize(14).fillColor(INK).text(`Invoice ${invoice.number}`, { continued: true });
  doc.fontSize(9).fillColor(GOLD).text(`  ${invoice.type}`, { continued: false });
  doc.fontSize(9).fillColor(INK_SOFT).text(`Date: ${invoice.createdAt.toLocaleDateString("en-IN")}    Status: ${invoice.status}`);
  if (invoice.dueDate) doc.fontSize(9).fillColor(INK_SOFT).text(`Due date: ${invoice.dueDate.toLocaleDateString("en-IN")}`);

  if (invoice.customer) {
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor(INK).text(`Bill to: ${invoice.customer.name}`);
    if (invoice.customer.phone) doc.fontSize(9).fillColor(INK_SOFT).text(invoice.customer.phone);
    if (invoice.customer.gstin) doc.fontSize(9).fillColor(INK_SOFT).text(`GSTIN: ${invoice.customer.gstin}`);
  }

  doc.moveDown(1);

  // Line items table
  const colX = { name: 50, qty: 300, price: 360, tax: 430, total: 480 };
  doc.fontSize(9).fillColor(INK_SOFT);
  doc.text("Item", colX.name, doc.y, { continued: false });
  doc.text("Qty", colX.qty, doc.y - doc.currentLineHeight());
  doc.text("Price", colX.price, doc.y - doc.currentLineHeight());
  doc.text("GST%", colX.tax, doc.y - doc.currentLineHeight());
  doc.text("Total", colX.total, doc.y - doc.currentLineHeight());
  doc.moveDown(0.3);
  doc.strokeColor(RULE).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.3);

  doc.fontSize(10).fillColor(INK);
  for (const item of invoice.items) {
    const y = doc.y;
    doc.text(item.name, colX.name, y, { width: 240 });
    doc.text(String(item.quantity), colX.qty, y);
    doc.text(`₹${item.unitPrice.toFixed(2)}`, colX.price, y);
    doc.text(`${item.taxRate}%`, colX.tax, y);
    doc.text(`₹${item.lineTotal.toFixed(2)}`, colX.total, y);
    doc.moveDown(0.6);
  }

  doc.moveDown(0.5);
  doc.strokeColor(RULE).moveTo(300, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.4);

  // Totals
  const totalRow = (label: string, value: string, bold = false) => {
    doc.fontSize(bold ? 12 : 10).fillColor(bold ? INK : INK_SOFT);
    doc.text(label, 380, doc.y, { continued: true, width: 100, align: "left" });
    doc.text(value, { align: "right" });
    doc.moveDown(0.3);
  };
  totalRow("Subtotal", `₹${invoice.subTotal.toFixed(2)}`);
  if (invoice.discount) totalRow("Discount", `-₹${invoice.discount.toFixed(2)}`);
  totalRow("GST", `₹${invoice.taxTotal.toFixed(2)}`);
  totalRow("Grand total", `₹${invoice.grandTotal.toFixed(2)}`, true);
  totalRow("Paid", `₹${invoice.amountPaid.toFixed(2)}`);
  const balance = invoice.grandTotal - invoice.amountPaid;
  if (balance > 0) totalRow("Balance due", `₹${balance.toFixed(2)}`, true);

  if (invoice.notes || invoice.terms) {
    doc.moveDown(1);
    if (invoice.notes) doc.fontSize(9).fillColor(INK_SOFT).text(`Notes: ${invoice.notes}`);
    if (invoice.terms) doc.fontSize(9).fillColor(INK_SOFT).text(`Terms: ${invoice.terms}`);
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor(INK_SOFT).text(`Generated by ${process.env.PRODUCT_NAME || "Buildwise"}`, 50, doc.page.height - 70, { align: "center", width: 495 });

    doc.end();
  });
}

export async function streamInvoicePdf(invoice: InvoiceForPdf, res: Response) {
  const pdf = await generateInvoicePdf(invoice);
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${invoice.number}.pdf"`);
  res.send(pdf);
}
