-- ============================================================
-- Khatabook+ — BigQuery schema
-- Mirrors every table in backend/prisma/schema.prisma exactly.
-- Replace `YOUR_PROJECT.khatabook` with your project + dataset.
--
-- Design notes:
-- - BigQuery has no ENUM type — enum fields are STRING with the
--   allowed values documented in a comment above each column.
--   Apps Script / Vercel should validate against these before insert.
-- - Every business-owned table is PARTITIONed by DATE(created_at)
--   and CLUSTERed by business_id — this is what makes "sales this
--   month for business X" queries cheap instead of full-table scans.
-- - IDs are STRING (UUIDs generated by your app, not BigQuery) so
--   they match the Postgres primary keys 1:1 if you ever need to
--   reconcile the two systems.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS `YOUR_PROJECT.khatabook`
OPTIONS (location = 'US');

-- ---------- Tenancy & identity ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.businesses` (
  id            STRING NOT NULL,
  name          STRING NOT NULL,
  gstin         STRING,
  address       STRING,
  logo_url      STRING,
  default_tax   FLOAT64 DEFAULT 0,
  drug_license_number  STRING,   -- medical vertical
  drug_license_expiry  TIMESTAMP,
  created_at    TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at);

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.users` (
  id             STRING NOT NULL,
  name           STRING NOT NULL,
  email          STRING NOT NULL,
  phone          STRING,
  password_hash  STRING NOT NULL,   -- never send plaintext passwords through this pipeline
  created_at     TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at);

-- role: one of OWNER | ADMIN | STAFF | SALESMAN | ACCOUNTANT
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.user_business` (
  id           STRING NOT NULL,
  user_id      STRING NOT NULL,
  business_id  STRING NOT NULL,
  role         STRING NOT NULL
)
CLUSTER BY business_id;

-- ---------- Contacts ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.customers` (
  id               STRING NOT NULL,
  business_id      STRING NOT NULL,
  name             STRING NOT NULL,
  phone            STRING,
  email            STRING,
  gstin            STRING,
  address          STRING,
  opening_balance  FLOAT64 DEFAULT 0,
  credit_limit     FLOAT64,          -- dealer/distributor credit limit
  loyalty_points   FLOAT64 DEFAULT 0,
  last_purchase_at TIMESTAMP,        -- drives dormant-customer win-back alerts
  updated_at       TIMESTAMP,
  created_at       TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.suppliers` (
  id               STRING NOT NULL,
  business_id      STRING NOT NULL,
  name             STRING NOT NULL,
  phone            STRING,
  email            STRING,
  gstin            STRING,
  address          STRING,
  opening_balance  FLOAT64 DEFAULT 0,
  created_at       TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id;

-- ---------- Inventory ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.items` (
  id                STRING NOT NULL,
  business_id       STRING NOT NULL,
  name              STRING NOT NULL,
  sku               STRING,
  barcode           STRING,
  category          STRING,
  unit              STRING DEFAULT 'PCS',
  sale_price        FLOAT64 DEFAULT 0,
  purchase_price    FLOAT64 DEFAULT 0,
  tax_rate          FLOAT64 DEFAULT 0,
  hsn_code          STRING,
  mrp               FLOAT64,
  is_mrp_inclusive  BOOL DEFAULT FALSE,
  current_stock     FLOAT64 DEFAULT 0,
  low_stock_alert   FLOAT64 DEFAULT 0,
  grade             STRING,   -- legacy freeform field, superseded by material_template_id below
  schedule_class    STRING,   -- medical vertical: Schedule H / H1 / X
  salt_composition  STRING,   -- medical vertical: e.g. "Paracetamol 500mg"
  requires_batch_tracking BOOL DEFAULT FALSE,
  material_template_id STRING,
  attributes        JSON,     -- template-specific fields: grade, TMT size, brick class, sand type...
  updated_at        TIMESTAMP,
  created_at        TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, barcode;

-- ---------- Metadata-driven vertical engine ----------
-- business_id NULL = a global starter template (Cement/Steel/Bricks/Sand)
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.material_templates` (
  id                STRING NOT NULL,
  business_id       STRING,
  name              STRING NOT NULL,
  unit_options      JSON NOT NULL,   -- e.g. ["Bag (50kg)", "Ton"]
  attribute_schema  JSON NOT NULL,   -- e.g. [{"key":"grade","label":"Grade","type":"select","options":[...]}]
  default_hsn_code  STRING,
  default_gst_rate  FLOAT64,
  created_at        TIMESTAMP NOT NULL
)
CLUSTER BY business_id;

-- reason: one of SALE | PURCHASE | ADJUSTMENT | RETURN | CHALLAN | OPENING
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.stock_movements` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  item_id      STRING NOT NULL,
  change       FLOAT64 NOT NULL,
  reason       STRING NOT NULL,
  ref_id       STRING,
  note         STRING,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, item_id;

-- ---------- Billing ----------

-- type: GST | NON_GST | POS
-- status: DRAFT | UNPAID | PARTIAL | PAID | CANCELLED
-- payment_mode: CASH | UPI | CARD | BANK_TRANSFER | CHEQUE
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.invoices` (
  id              STRING NOT NULL,
  business_id     STRING NOT NULL,
  customer_id     STRING,
  number          STRING NOT NULL,
  type            STRING DEFAULT 'GST' NOT NULL,
  status          STRING DEFAULT 'UNPAID' NOT NULL,
  sub_total       FLOAT64 NOT NULL,
  discount        FLOAT64 DEFAULT 0,
  tax_total       FLOAT64 DEFAULT 0,
  grand_total     FLOAT64 NOT NULL,
  amount_paid     FLOAT64 DEFAULT 0,
  payment_mode    STRING,
  due_date        TIMESTAMP,
  notes           STRING,
  terms           STRING,
  client_request_id STRING,
  is_e_invoice    BOOL DEFAULT FALSE,
  e_invoice_irn   STRING,
  is_e_way_bill   BOOL DEFAULT FALSE,
  is_rcm          BOOL DEFAULT FALSE,   -- reverse charge — buyer pays GST directly
  tcs_amount      FLOAT64 DEFAULT 0,    -- tax collected at source (dealer sales)
  vehicle_number  STRING,               -- cement/bulk-dispatch vertical
  transporter_id  STRING,
  updated_at      TIMESTAMP,
  created_at      TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, status;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.invoice_items` (
  id          STRING NOT NULL,
  invoice_id  STRING NOT NULL,
  item_id     STRING,
  name        STRING NOT NULL,
  quantity    FLOAT64 NOT NULL,
  unit_price  FLOAT64 NOT NULL,
  discount    FLOAT64 DEFAULT 0,
  tax_rate    FLOAT64 DEFAULT 0,
  line_total  FLOAT64 NOT NULL
)
CLUSTER BY invoice_id;

-- status: DRAFT | RECEIVED | PARTIAL | PAID | CANCELLED
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.purchase_bills` (
  id                STRING NOT NULL,
  business_id       STRING NOT NULL,
  supplier_id       STRING,
  number            STRING NOT NULL,
  status            STRING DEFAULT 'DRAFT' NOT NULL,
  sub_total         FLOAT64 NOT NULL,
  discount          FLOAT64 DEFAULT 0,
  tax_total         FLOAT64 DEFAULT 0,
  grand_total       FLOAT64 NOT NULL,
  amount_paid       FLOAT64 DEFAULT 0,
  payment_mode      STRING,
  due_date          TIMESTAMP,
  reference_number  STRING,
  client_request_id STRING,
  updated_at        TIMESTAMP,
  created_at        TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, status;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.purchase_bill_items` (
  id          STRING NOT NULL,
  bill_id     STRING NOT NULL,
  item_id     STRING,
  name        STRING NOT NULL,
  quantity    FLOAT64 NOT NULL,
  unit_price  FLOAT64 NOT NULL,
  discount    FLOAT64 DEFAULT 0,
  tax_rate    FLOAT64 DEFAULT 0,
  line_total  FLOAT64 NOT NULL
)
CLUSTER BY bill_id;

-- ---------- Estimates / Quotations ----------

-- status: OPEN | CONVERTED | EXPIRED
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.estimates` (
  id                    STRING NOT NULL,
  business_id           STRING NOT NULL,
  customer_id           STRING,
  number                STRING NOT NULL,
  status                STRING DEFAULT 'OPEN' NOT NULL,
  sub_total             FLOAT64 NOT NULL,
  tax_total             FLOAT64 DEFAULT 0,
  grand_total           FLOAT64 NOT NULL,
  converted_invoice_id  STRING,
  valid_until           TIMESTAMP,
  notes                 STRING,
  terms                 STRING,
  client_request_id    STRING,
  created_at            TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.estimate_items` (
  id           STRING NOT NULL,
  estimate_id  STRING NOT NULL,
  item_id      STRING,
  name         STRING NOT NULL,
  quantity     FLOAT64 NOT NULL,
  unit_price   FLOAT64 NOT NULL,
  tax_rate     FLOAT64 DEFAULT 0,
  line_total   FLOAT64 NOT NULL
)
CLUSTER BY estimate_id;

-- ---------- Delivery Challans ----------

-- status: PENDING | DELIVERED | CANCELLED
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.delivery_challans` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  customer_id  STRING,
  number       STRING NOT NULL,
  status       STRING DEFAULT 'PENDING' NOT NULL,
  vehicle_number STRING,
  transporter_id STRING,
  notes        STRING,
  client_request_id STRING,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.delivery_challan_items` (
  id          STRING NOT NULL,
  challan_id  STRING NOT NULL,
  item_id     STRING,
  name        STRING NOT NULL,
  quantity    FLOAT64 NOT NULL
)
CLUSTER BY challan_id;

-- ---------- Expenses (manual + OCR/AI-categorized) ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.expenses` (
  id                      STRING NOT NULL,
  business_id             STRING NOT NULL,
  supplier_id             STRING,
  category                STRING,
  amount                  FLOAT64 NOT NULL,
  tax_amount              FLOAT64 DEFAULT 0,
  note                    STRING,
  source_image_url        STRING,
  ai_category_confidence  FLOAT64,   -- NULL if manually entered, 0-1 if AI-tagged
  created_at              TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, category;

-- ---------- Payments ----------

-- mode: CASH | UPI | CARD | BANK_TRANSFER | CHEQUE
-- direction: IN | OUT
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.payments` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  customer_id  STRING,
  supplier_id  STRING,
  invoice_id   STRING,
  amount       FLOAT64 NOT NULL,
  mode         STRING NOT NULL,
  direction    STRING NOT NULL,
  note         STRING,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, direction;

-- ---------- Field staff tracking ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.salesman_logs` (
  id          STRING NOT NULL,
  user_id     STRING NOT NULL,
  latitude    FLOAT64 NOT NULL,
  longitude   FLOAT64 NOT NULL,
  note        STRING,
  created_at  TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY user_id;

-- ---------- Credit / Debit Notes ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.credit_notes` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  customer_id  STRING,
  invoice_id   STRING,
  number       STRING NOT NULL,
  reason       STRING,
  amount       FLOAT64 NOT NULL,
  tax_amount   FLOAT64 DEFAULT 0,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.credit_note_items` (
  id             STRING NOT NULL,
  credit_note_id STRING NOT NULL,
  name           STRING NOT NULL,
  quantity       FLOAT64 NOT NULL,
  unit_price     FLOAT64 NOT NULL,
  line_total     FLOAT64 NOT NULL
)
CLUSTER BY credit_note_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.debit_notes` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  supplier_id  STRING,
  number       STRING NOT NULL,
  reason       STRING,
  amount       FLOAT64 NOT NULL,
  tax_amount   FLOAT64 DEFAULT 0,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.debit_note_items` (
  id            STRING NOT NULL,
  debit_note_id STRING NOT NULL,
  name          STRING NOT NULL,
  quantity      FLOAT64 NOT NULL,
  unit_price    FLOAT64 NOT NULL,
  line_total    FLOAT64 NOT NULL
)
CLUSTER BY debit_note_id;

-- ---------- Batch/expiry & unit conversion (medical, cement) ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.item_batches` (
  id            STRING NOT NULL,
  item_id       STRING NOT NULL,
  batch_number  STRING NOT NULL,
  quantity      FLOAT64 NOT NULL,
  expiry_date   TIMESTAMP,
  mfg_date      TIMESTAMP,
  created_at    TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY item_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.unit_conversions` (
  id         STRING NOT NULL,
  item_id    STRING NOT NULL,
  from_unit  STRING NOT NULL,
  to_unit    STRING NOT NULL,
  factor     FLOAT64 NOT NULL
)
CLUSTER BY item_id;

-- ---------- Multi-warehouse ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.warehouses` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  name         STRING NOT NULL,
  address      STRING,
  is_default   BOOL DEFAULT FALSE,
  created_at   TIMESTAMP NOT NULL
)
CLUSTER BY business_id;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.warehouse_stock` (
  id            STRING NOT NULL,
  warehouse_id  STRING NOT NULL,
  item_id       STRING NOT NULL,
  quantity      FLOAT64 DEFAULT 0
)
CLUSTER BY warehouse_id, item_id;

-- ---------- GST filing & compliance ----------
-- return_type: GSTR1 | GSTR3B
-- status: DRAFT | READY | FILED | ERROR
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.gst_filings` (
  id             STRING NOT NULL,
  business_id    STRING NOT NULL,
  return_type    STRING NOT NULL,
  period         STRING NOT NULL,        -- "2026-08" or "2026-Q2"
  status         STRING DEFAULT 'DRAFT' NOT NULL,
  taxable_value  FLOAT64 DEFAULT 0,
  tax_collected  FLOAT64 DEFAULT 0,
  itc_claimed    FLOAT64 DEFAULT 0,
  gsp_reference  STRING,                 -- ack number, once actually filed via a GSP
  filed_at       TIMESTAMP,
  error_detail   STRING,
  prepared_by_user_id STRING,
  created_at     TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, return_type;

-- match_status: MATCHED | MISMATCH | MISSING_IN_2A | MISSING_IN_BOOKS | PENDING
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.itc_reconciliations` (
  id              STRING NOT NULL,
  business_id     STRING NOT NULL,
  supplier_gstin  STRING NOT NULL,
  invoice_number  STRING NOT NULL,
  our_amount      FLOAT64,
  gstn_amount     FLOAT64,
  match_status    STRING DEFAULT 'PENDING' NOT NULL,
  created_at      TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, match_status;

-- status: PENDING | GENERATED | CANCELLED | EXPIRED
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.eway_bills` (
  id              STRING NOT NULL,
  invoice_id      STRING NOT NULL,
  ewb_number      STRING,
  vehicle_number  STRING,
  transporter_id  STRING,
  status          STRING DEFAULT 'PENDING' NOT NULL,
  valid_until     TIMESTAMP,
  created_at      TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY invoice_id;

-- ---------- Customer growth ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.loyalty_transactions` (
  id           STRING NOT NULL,
  customer_id  STRING NOT NULL,
  points       FLOAT64 NOT NULL,  -- positive = earned, negative = redeemed
  reason       STRING,
  invoice_id   STRING,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY customer_id;

-- channel: WHATSAPP | SMS      status: DRAFT | SENT
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.campaigns` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  channel      STRING NOT NULL,
  message      STRING NOT NULL,
  segment      STRING NOT NULL,   -- high_value | dormant | frequent | all
  status       STRING DEFAULT 'DRAFT' NOT NULL,
  sent_count   INT64 DEFAULT 0,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id;

-- channel: WHATSAPP | SMS | EMAIL     status: PENDING | SENT | FAILED
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.payment_reminders` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  invoice_id   STRING,
  customer_id  STRING,
  channel      STRING NOT NULL,
  status       STRING DEFAULT 'PENDING' NOT NULL,
  sent_at      TIMESTAMP,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, status;

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.compliance_documents` (
  id                STRING NOT NULL,
  business_id       STRING NOT NULL,
  uploaded_by_user_id STRING NOT NULL,
  document_type     STRING NOT NULL,
  period            STRING,
  file_name         STRING NOT NULL,
  mime_type         STRING NOT NULL,
  storage_url       STRING,
  storage_path      STRING,
  created_at        TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, document_type;

-- ---------- Step 6: Security, audit, credit, reconciliation ----------

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.audit_logs` (
  id           STRING NOT NULL,
  business_id  STRING NOT NULL,
  user_id      STRING,
  action       STRING NOT NULL,   -- e.g. "invoice.create", "item.adjust_stock"
  entity_type  STRING NOT NULL,
  entity_id    STRING,
  detail       JSON,
  created_at   TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, entity_type;

-- status: UNMATCHED | MATCHED | IGNORED
CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.bank_statement_lines` (
  id                  STRING NOT NULL,
  business_id         STRING NOT NULL,
  date                TIMESTAMP NOT NULL,
  description         STRING NOT NULL,
  amount              FLOAT64 NOT NULL,
  matched_payment_id  STRING,
  status              STRING DEFAULT 'UNMATCHED' NOT NULL,
  created_at          TIMESTAMP NOT NULL
)
PARTITION BY DATE(date)
CLUSTER BY business_id, status;

-- ============================================================
-- Sync/automation metadata — problem → solution log
--
-- Every ingest pipeline hits recurring failure modes (a row Apps
-- Script sent twice, a device clock skew causing a bad updatedAt,
-- a GSP call that times out). Rather than losing that context in
-- Vercel logs that expire, log it here — it's queryable, joins
-- against the business it happened to, and survives as an audit
-- trail for support/debugging.
-- ============================================================

CREATE TABLE IF NOT EXISTS `YOUR_PROJECT.khatabook.sync_events` (
  id            STRING NOT NULL,
  business_id   STRING,
  source        STRING NOT NULL,   -- e.g. "appscript", "offline_client", "gsp"
  event_type    STRING NOT NULL,   -- e.g. "push_conflict", "gsp_timeout", "duplicate_row"
  table_name    STRING,
  row_id        STRING,
  problem       STRING NOT NULL,   -- what went wrong, in plain language
  resolution    STRING,            -- how it was resolved, or NULL if still open
  status        STRING DEFAULT 'OPEN' NOT NULL,  -- OPEN | RESOLVED | IGNORED
  created_at    TIMESTAMP NOT NULL
)
PARTITION BY DATE(created_at)
CLUSTER BY business_id, status;
